### ISSUE TITLE
Dragable card widget

### ISSUE THREAD

**Issue by gabyfle** [lo21-p23-project/lo21-project#48]
- Do a dragable card widget to be able to drag shotten-totten cards around
- The widget should contain an image
- It should be able to be clicked on (not just dragged)
- It should be able to be selected

**Comment by gabyfle** [comment]
@col-roussel this is so far what I got


https://github.com/lo21-p23-project/lo21-project/assets/18049206/c5e46d35-e599-4734-a20f-f8818edfbd8d

**Comment by col-roussel** [comment]
That looks amazing bro!!

**Comment by gabyfle** [comment]
@col-roussel 

https://github.com/lo21-p23-project/lo21-project/assets/18049206/1e1daf2c-dcc1-41db-99ce-58ef9022757f
